name: Compile

on:
  workflow_dispatch:
    inputs:
      KERNEL_URL:
        description: 'KERNEL_URL'
        required: true
      KERNEL_BRANCH:
        description: 'KERNEL_BRANCH'
        required: true
      CLANG_URL:
        description: 'ClANG_VERSION'
        required: true
        default: https://gitlab.com/mcdofrenchfreis/android-clang-14.0.7.git
      CLANG_BRANCH:
        description: 'ClANG_BRANCH'
        required: true
      DEFCONFIG:
        description: 'KERNEL_DEFCONFIG'
        required: true
        default: fleur_defconfig

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "KERNEL url: ${{ github.event.inputs.KERNEL_URL }}"
        echo "KERNEL branch: ${{ github.event.inputs.KERNEL_BRANCH }}"
        echo "defconfig: ${{ github.event.inputs.DEFCONFIG }}"
        echo "::endgroup::"

     # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    - name: Prepare the environment
      run: |
        sudo apt update -y
        sudo apt install -y \
          bc bison build-essential ca-certificates clang curl cpio \
          flex gcc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
          git libarchive-tools libc6-dev libelf-dev libffi-dev \
          libncurses5-dev libreadline-dev libsqlite3-dev libssl-dev \
          lld llvm make nano neofetch openssl pigz python2 python3 \
          software-properties-common ssh sudo wget zip zlib1g \
          zlib1g-dev

    - name: Clone Clang
      run: |
        git clone --b "${{ github.event.inputs.CLANG_BRANCH }}" \
          "${{ github.event.inputs.CLANG_URL }}" toolchain

    - name: Clone Kernel Source
      run: |
        git clone --b "${{ github.event.inputs.KERNEL_BRANCH }}" \
          "${{ github.event.inputs.KERNEL_URL }}" kernel

    - name: Clone AnyKernel3
        run: |
          git clone https://github.com/farelfair/AnyKernel3.git

    - name: Copy image to AnyKernel3
        run: |
          cp kernel/out/arch/arm64/boot/Image
          cd AnyKernel3
          zip -r9 ../Kernel-${{ github.event.inputs.RELEASE_NAME }}.zip ./*

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.RELEASE_NAME }}
        name: Release - ${{ github.event.inputs.RELEASE_NAME }}
        body: |
          ✅ Compiled kernel: `${{ github.event.inputs.RELEASE_NAME }}`
          🔧 Defconfig: `${{ github.event.inputs.DEFCONFIG }}`  
          🛠️ Clang: `${{ github.event.inputs.CLANG_URL }}`
        files: |
          Kernel-${{ github.event.inputs.RELEASE_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}