name: Compile

on:
  workflow_dispatch:
    inputs:
      KERNEL_URL:
        description: 'KERNEL_URL'
        required: true
      KERNEL_BRANCH:
        description: 'KERNEL_BRANCH'
        required: true
      DEFCONFIG:
        description: 'KERNEL_DEFCONFIG'
        required: true

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Print Environment Variables
      run: |
        echo "::group::User Environment Variables"
        echo "KERNEL url: ${{ github.event.inputs.KERNEL_URL }}"
        echo "KERNEL branch: ${{ github.event.inputs.KERNEL_BRANCH }}"
        echo "defconfig: ${{ github.event.inputs.DEFCONFIG }}"
        echo "::endgroup::"

     # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    - name: Install Dependecies
      run: |
        sudo apt update -y
        sudo apt install -y \
          bc bison build-essential ca-certificates clang curl cpio \
          flex gcc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
          git libarchive-tools libc6-dev libelf-dev libffi-dev \
          libncurses5-dev libreadline-dev libsqlite3-dev libssl-dev \
          lld llvm make nano neofetch openssl pigz python2 python3 \
          software-properties-common ssh sudo wget zip zlib1g \
          zlib1g-dev
        neofetch